### ISSUE TITLE
Added in backwards compatibility for older .NET frameworks and moving to .NET standard

### ISSUE THREAD

**Issue by glitch100** [glitch100/BinanceDotNet#11]
A few people have reached out in regards to installed on .NET451 or .NET452 . This should be addressed.  -
- Remove NLog and rely on built in logging abstractions.
- Take opportunity to move abstractions to new class library

**Comment by robbaman** [comment]
In addition to the NLog refactoring, may I be so bold to suggest we refactor the project to use the format Microsoft uses for their dotnet core packages. I would suggest to make the following changes:

1. Separate the implementation from the interfaces by adding a package (project) *BinanceExchange.API.Abstractions* for the interfaces.
2. Add a class with extension methods for the IServiceCollection class to register the Binance classes with an IOC container.
3. Use the Options pattern to setup the configuration

I'm willing to help out by making these modifications for you to review and if needed improve upon, but I'm only going to put the time in if you're seriously considering accepting these changes. Otherwise it'd just be a waste of time for me to set this up for you to review.

**Comment by glitch100** [comment]
Hi @robbaman,

Thanks for the feedback. I have updated the above issue with some of your suggestions. I had planned a huge refactor to move certain parts around, introduce more unit testing, and move around some dependencies and revisit caching, and utilise it across endpoints if users want to.

As for the other suggestions they sound pretty nice and would be great things to pursue. Right now I am working on solving bugs and just making sure library is good as it's being more widely adopted however can you make an issue for the `IServiceCollection` Microsoft.Extensions and the `Options` pattern, and we can revisit them after the next major release with bug fixes and the primary support?

**Comment by robbaman** [comment]
Sure, gotta get to bed now though, but I'll try to find some time to write it up in proper detail tomorrow. 

Also as a final todo for the list: Add CancellationTokens to the async methods so they may be cancelled if needed.

**Comment by glitch100** [comment]
Yea CancellationTokens are a must to be honest. I unfortunately rushed a lot of implementation to meet the deadline, hence taking time to make small improvements over time. Trying to balance with work of course, so thanks again for any contribution

**Comment by glitch100** [comment]
Going to add new issues and close this one @robbaman , feel free to take them up, and they can be for the next release (so I can get 4.0.0 out so that others can take advantage of fixes)
