### ISSUE TITLE
What does CompressedAggregateTradeResponse.WasBuyerMaker mean?

### ISSUE THREAD

**Issue by menkaur** [glitch100/BinanceDotNet#113]
The field name does not sufficiently  describe it's meaning.

There are 2 interpretations:

1. The trade was made by the buyer (someone took a ask)
2. Buyer was market making, and the trade actually is a sell (someone took an bid)

Please, clarify what it means if this field is true

**Comment by Bladerender** [comment]
I checked with binance native client and it shows red for deal when tradeInfo.Model.IsBuyerMaker == true and green when it's false. So it's #2.

My code (commented and already forgotten). 
if (tradeInfo.Model.IsBuyerMaker == true)
                {
                    tradeInfo.DealType = DealType.Sell;
                }

But it's basically crap trying to forecast market movement by trying to calculate % of sell/buy deals or volume of sell/buy deals. Believe me. Because that taker/maker thing works only if trades rate per minute is maximum 10. But if it's 100-2300 per second (2300 that is maximum i've seen), everydoby makers because orders list moving back and forth to fast. I would recommend to forget about it in case you trying to analize/forecast the market.

**Comment by menkaur** [comment]
Your're right, I've seen the market move up and down with both high buy
pressure or sell pressure. But I think that if some information is
available, it's better to use it. When I chart the ticks, I do buys with
green and sells with red, and I like this much better compared with all
ticks having the same color
