### ISSUE TITLE
Order book manage with combined @depth socket stream, lost changes

### ISSUE THREAD

**Issue by skarpyak** [glitch100/BinanceDotNet#117]
## Issue Overview
very often I receive messages like this:
{"stream":"ethbtc@depth","data":{"e":"depthUpdate","E":1533979317013,"s":"ETHBTC","U":286020835,"u":286020847,"b":[["0.05193900","1.59700000",[]], ["0.05193800","2.70100000",[]],["0.05193700","0.00000000",[]],["0.05088900","0.16400000",[]]],"a":[["0.05196000","0.23800000",[]],["0.05196100","8.66700000",[]],["0.05196200","0.00000000",[]],["0.05253900","0.08200000",[]],["0.05256900","3.00000000",[]]]}}

"U" = 286020835
'u' = 286020847
I think this means message should contain 13 events, but it contains only 9, looks like 4 events lost, can somebody explain this?

When I try apply changes on order book and do compare with current order book it is almost always have differences which i can't find in messages

#### Repro Steps
1. setup combined @depth socket 
2. listen messages

**Comment by fl4p** [comment]
I'm just experiencing similar issues here. After some hours my local book differs from the actual.

How do you synchronize the first snapshot with the WS updates? I think the example in the readme of this repo is incorrect. It misses a buffer that collects some messages ahead and then fetches the snapshot. Also it does not check for the `U`, which is completely missing in the code.


I run a parallel stream with a nodejs application which does not appear to have this. And I just checked it, the `u`-`U` difference does not always equal to the number of updated levels. It can be more or even less.
This is ok because, assuming that `u` counts the mutations to the order book and you receive an update every second, you can have multiple of theses events at the same price level, and the server just sends you the final size. In rare cases events might neutralize each other so the size stays the same.

Still, trying to get this working in C#

**Comment by skarpyak** [comment]
@fl4p thank you for explanation, it helps me a lot to understand why u-U not always the same as items count
I have good progress, and my local orderBook works ok, only in cases if I trying check order book with "updateId" between  "u" and "U" it is always incorrect because it is not possible detect which of items should be present/absent

**Comment by skarpyak** [comment]
not an issue
